spring:
  application:
    name: ChatterHub
  profiles:
    active: dev
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:supergurizes@gmail.com}
    password: ${MAIL_PASSWORD:etym zgbs jdmf ardo}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
# ----------------------------------------------------
# PERFIL DEV (Local / Testes em memória ou MySQL local)
# ----------------------------------------------------
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:chatterhubdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

---
# ----------------------------------------------------
# PERFIL PROD (VPS / Docker / MySQL ou Postgres)
# ----------------------------------------------------
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:chatterhub}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}