spring:
  application:
    name: ChatterHub
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:vps}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
# ----------------------------------------------------
# PERFIL DEV (Banco H2 em Memória para Testes Locais)
# ----------------------------------------------------
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:chatterhubdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

---
# ----------------------------------------------------
# PERFIL VPS (Banco MySQL na VPS)
# ----------------------------------------------------
spring:
  config:
    activate:
      on-profile: vps
  datasource:
    url: jdbc:mysql://${DB_HOST:179.199.128.219}:${DB_PORT:3306}/${DB_NAME:chatterhubdb}?serverTimezone=America/Sao_Paulo&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:razza-chatterhubDB}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}